### PR TITLE
add icons for KXStudio applications suite

### PR DESCRIPTION
**Pull request by BillyDM**
I've added icons for the KXStudio applications suite, which is a suite of Linux applications used to configure and patch audio software and plugins together using the jack audio backend. https://kx.studio/Applications

These are mostly just copied from the Papirus icon theme but with the colors tweaked to fit the Flatery theme.

The most important applications are Cadence, Carla, and Carla Control.
cadence
carla
carla-control

The other four (Catia, Catarina, Claudia, and Claudia-lancher) are just extras/rarely used software, but I figured I would add them to complete the set even if they aren't the "best" looking of icons.

catia
catarina
claudia
claudio-launcher

### CODE REVIEW

**Comment by BillyDM** [comment]
Although wait, I just noticed that my icons are bigger than all the other "square"-like icons. Let me fix that real quick.

**Comment by BillyDM** [comment]
Okay, I fixed the size.

**Comment by cbrnix** [comment]
Thanks for the input. I’ll see how I’m free. The fact is that for these icons I use the palette
https://github.com/cbrnix/Flatery-DIY/tree/main/Flatery%20DIY/Palette%20for%20inkscape
For red, the value is 400.
I can correct them if you send me a package. And bring the dimensions exactly right. This does not plead for your input. thanks again

**Comment by BillyDM** [comment]
> I can correct them if you send me a package.

What do you mean by "send you a package"?

**Comment by BillyDM** [comment]
Oh, I just now noticed the `Flatery-DIY` repo. That would have been helpful to know existed. I pretty much just manually resized and copied each icon into the respective folders.

Maybe you could mention the `Flatery-DIY` repo in the readme of the `Flatery` repo so no one makes this mistake again?

**Comment by cbrnix** [comment]
> > I can correct them if you send me a package.
> 
> What do you mean by "send you a package"?

Sorry, I was in a hurry. I mean, if you put these icons in an archive, I will bring them in line with the theme

**Comment by BillyDM** [comment]
[kxstudio-icons.zip](https://github.com/cbrnix/Flatery/files/7848176/kxstudio-icons.zip)

Alright, here you go. I also inverted the colors on a few of them because I thought it looked a bit better.

**Comment by cbrnix** [comment]
Done

**Pull request closed without merging**
